FROM keboola/docker-amazonlinux-php:latest

# node + yarn
RUN curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
RUN curl --silent https://dl.yarnpkg.com/rpm/yarn.repo > /etc/yum.repos.d/yarn.repo
RUN yum -y install findutils nodejs npm yarn python27 wget

# install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin/ --filename=composer

# working directory
WORKDIR /var/task
COPY . .

RUN composer install $COMPOSER_FLAGS

RUN yarn global add serverless@1.45
