FROM github-token-scanning

RUN curl --silent --location https://rpm.nodesource.com/setup_10.x | bash - \
    && curl --silent https://dl.yarnpkg.com/rpm/yarn.repo > /etc/yum.repos.d/yarn.repo \
    && yum -y install findutils nodejs npm yarn \
    && yum clean all

RUN yarn global add serverless@1.43 \
    && yarn install
